name: Build OpenWrt IPK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64_generic]   # 同时构建 x86_64 和 ARM64
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup OpenWrt SDK
        run: |
          # 下载对应架构的 SDK
          mkdir sdk
          cd sdk
          wget https://downloads.openwrt.org/releases/23.05.3/targets/${{ matrix.arch == 'x86_64' && 'x86/64' || 'armsr/armv8' }}/openwrt-sdk-23.05.3-${{ matrix.arch == 'x86_64' && 'x86-64' || 'armsr-armv8' }}_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xJf openwrt-sdk-*.tar.xz --strip-components=1

      - name: Prepare environment
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          mkdir -p package/luci-app-jxustportal
          cp -r $GITHUB_WORKSPACE/luci package/luci-app-jxustportal/
          cp $GITHUB_WORKSPACE/Makefile package/luci-app-jxustportal/

      - name: Build package
        run: |
          cd sdk
          make package/luci-app-jxustportal/compile V=s

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-jxustportal-${{ matrix.arch }}
          path: |
            sdk/bin/packages/*/*/luci-app-jxustportal*.ipk
